<a href="https://colab.research.google.com/github/pdivya-mca/NumPy-Assignment/blob/main/Assignment_2_Numpy_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**



### **1. Import the numpy package under the name `np` (★☆☆)**
(**hint**: import … as …)

In [ ]:
import numpy as np

### **2. Print the numpy version and the configuration (★☆☆)**

(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)

1.21.6


In [ ]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

## ***3. Create a null vector of size 10 (★☆☆) ***
(**hint**: np.zeros)

In [ ]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## ***4.  How to find the memory size of any array (★☆☆)***
(**hint**: size, itemsize)

In [ ]:
print(x.size) #size of an array

10


In [ ]:
print(x.itemsize) # size of single element of ana array

8


### ***5.  How to get the documentation of the numpy add function from the command line? (★☆☆) ***
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

### **6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)**
(**hint**: array\[4\])

In [ ]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## ***7.  Create a vector with values ranging from 10 to 49 (★☆☆) ***
(**hint**: np.arange)

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## ***8.  Reverse a vector (first element becomes last) (★☆☆) ***
(**hint**: array\[::-1\])

In [ ]:
x=[1,2,3,4,5]
x[::-1]

[5, 4, 3, 2, 1]

## ***9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) ***
(**hint**: reshape)

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## ***10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) ***
(**hint**: np.nonzero)

In [ ]:
x=[1,2,0,0,4,0]
np.nonzero(x)

(array([0, 1, 4]),)

## ***11. Create a 3x3 identity matrix (★☆☆) ***
(**hint**: np.eye)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## ***12. Create a 3x3x3 array with random values (★☆☆) ***
(**hint**: np.random.random)

In [ ]:
np.random.random((3,3,3))

array([[[0.12552402, 0.03761838, 0.29838475],
        [0.30055844, 0.95346415, 0.23871003],
        [0.18437805, 0.90393906, 0.885431  ]],

       [[0.2482282 , 0.48635809, 0.27413671],
        [0.55602908, 0.47657776, 0.36949706],
        [0.41113059, 0.38009279, 0.39223043]],

       [[0.57130818, 0.54634865, 0.34622136],
        [0.25974093, 0.43952139, 0.33905128],
        [0.47633965, 0.32655119, 0.93765677]]])

## ***13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) ***
(**hint**: min, max)

In [ ]:
x=np.random.random((10,10))
x

array([[0.12883204, 0.63656492, 0.04928488, 0.75629567, 0.43975722,
        0.97755374, 0.23966693, 0.13799675, 0.83672615, 0.97009848],
       [0.95276699, 0.61170311, 0.39533583, 0.7791011 , 0.18055429,
        0.48738167, 0.2758223 , 0.62973096, 0.96496339, 0.24467451],
       [0.3991995 , 0.31664242, 0.36055005, 0.15640875, 0.7358679 ,
        0.9108967 , 0.03571251, 0.83569065, 0.86857278, 0.13224866],
       [0.49682291, 0.30302241, 0.06678695, 0.08233631, 0.05710401,
        0.51630094, 0.41572298, 0.00960852, 0.76762887, 0.5208889 ],
       [0.27702881, 0.00895595, 0.18833253, 0.23021909, 0.57708984,
        0.15333429, 0.64561319, 0.94747607, 0.77400259, 0.55872019],
       [0.34205762, 0.59175356, 0.861053  , 0.89610565, 0.01162341,
        0.72150334, 0.52528498, 0.18701999, 0.51294327, 0.65210107],
       [0.15268694, 0.01344064, 0.03750524, 0.37163396, 0.2627494 ,
        0.95334785, 0.00636536, 0.84478389, 0.67148884, 0.59440652],
       [0.09111761, 0.12021797, 0.8103425

In [ ]:
np.min(x)

0.006365355127730288

In [ ]:
np.max(x)

0.9953469364415892

## ***14. Create a random vector of size 30 and find the mean value (★☆☆) ***
(**hint**: mean)

In [ ]:
x=np.random.rand(30)
x

array([0.19380333, 0.70470141, 0.20779362, 0.15237085, 0.18034972,
       0.31418564, 0.81139876, 0.85373452, 0.18585269, 0.70889756,
       0.32191691, 0.26991921, 0.0661836 , 0.99819829, 0.80217901,
       0.60310484, 0.29443716, 0.35600544, 0.86683332, 0.86852543,
       0.61292469, 0.61278894, 0.62051444, 0.46124972, 0.70549111,
       0.28054028, 0.25120463, 0.88892908, 0.14681747, 0.43749678])

In [ ]:
np.mean(x)

0.49261161580981855

## ***15. Create a 2d array with 1 on the border and 0 inside (★☆☆) ***
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x=np.ones((5,5))
x[1:-1, 1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## ***16. How to add a border (filled with 0's) around an existing array? (★☆☆) ***
(**hint**: np.pad)

In [ ]:
x=np.ones((5,5))
np.pad(x,pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

## ***17. What is the result of the following expression? (★☆☆) ***
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


## ***18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) ***
(**hint**: np.diag)

In [ ]:
x = np.diag([1,2,3,4], k=-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

## ***19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) ***
(**hint**: array\[::2\])

In [ ]:
x = np.ones((8,8))
x[::2]=0
x[::2,1::2] = 1
x[1::2,1::2]=0
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

### **20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?**
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


## ***21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) ***
(**hint**: np.tile)

In [ ]:
x = np.eye(2)
y = np.tile(x,(8,8))
y

array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,

22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

### ***#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) ***
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

## ***24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) ***
(**hint**: np.dot | @)

In [ ]:
x1 = np.arange(1,16).reshape(5,3)
x2 = np.arange(1,7).reshape(3,2)
z = np.dot(x1,x2)
print(x1, x2, z ,sep='\n')

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[1 2]
 [3 4]
 [5 6]]
[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


### ***#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) ***
(**hint**: >, <=)

In [ ]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


## ***26. What is the output of the following script? (★☆☆) ***
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(np.sum(range(5),-1))
from numpy import *
print(np.sum(range(5),-1))

10
10


## **27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)**

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z=np.array([1,2,3,4,5])

In [ ]:
Z**Z

array([   1,    4,   27,  256, 3125])

In [ ]:
2 << Z >> 2

array([ 1,  2,  4,  8, 16])

In [ ]:
Z <- Z

array([False, False, False, False, False])

In [ ]:
1j*Z

array([0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j])

In [ ]:
Z/1/1

array([1., 2., 3., 4., 5.])

In [ ]:
Z< Z >Z

ValueError: ignored

## **28. What are the result of the following expressions?**

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [ ]:
np.array(0) // np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [ ]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

## **29. How to round away from zero a float array ? (★☆☆)**
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 4.  7. -2.  8.  4. -2. 10. -2. -1. -8.]


## **30. How to find common values between two arrays? (★☆☆)**
(**hint**: np.intersect1d)

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
np.intersect1d(a,b)

array([4, 5])

## **31. How to ignore all numpy warnings (not recommended)? (★☆☆)**
(**hint**: np.seterr, np.errstate)

In [ ]:
data = np.random.random(1000).reshape(10, 10,10) * np.nan
np.seterr(all="ignore")
np.nanmedian(data, axis=[1, 2])

/usr/local/lib/python3.7/dist-packages/numpy/lib/nanfunctions.py:1120: RuntimeWarning: All-NaN slice encountered
  overwrite_input=overwrite_input)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

## **32. Is the following expressions true? (★☆☆)**
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


## **33. How to get the dates of yesterday, today and tomorrow? (★☆☆)**

In [ ]:
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
print("Yesterday:",yesterday)
yesterday=np.datetime64('today','D')
print("Today:",yesterday)
yesterday=np.datetime64('today','D')+np.timedelta64(1,'D')
print("Tomorrow:",yesterday)

Yesterday: 2022-11-20
Today: 2022-11-21
Tomorrow: 2022-11-22


## ***34. How to get all the dates corresponding to the month of July 2016? (★★☆) ***
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
np.arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆) bold text
hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A=np.ones(5)*3
B=np.ones(5)
np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2, out= A)
np.multiply(A,B,out=A)

array([-6., -6., -6., -6., -6.])

# ***36. Extract the integer part of a random array using 5 different methods (★★☆) ***
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
X=np.random.rand(10)
print(X-X%1)
print(np.floor(X))
print(np.ceil(X))
print(X.astype(int))
print(np.trunc(X))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## **37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)**

In [ ]:
x = np.arange(5)
np.tile(x,(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

## ***38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) ***
(**hint**: np.fromiter)

In [ ]:
def generate():
    for x in range(10):
        yield x
x = np.fromiter(generate(),dtype=float)
print(x)

## ***39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) ***
(**hint**: np.linspace)

In [ ]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


## ***40. Create a random vector of size 10 and sort it (★★☆) ***
(**hint**: sort)

In [ ]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.10997411 0.25677047 0.41341952 0.65913345 0.67479968 0.73717861
 0.7562941  0.77613896 0.83753463 0.94005192]


## ***41. How to sum a small array faster than np.sum? (★★☆) ***
(**hint**: np.add.reduce)

In [ ]:
Z = np.arange(5)
np.add.reduce(Z)

10

# ***42. Consider two random array A and B, check if they are equal (★★☆) ***
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.randint(0,3,5)
B = np.random.randint(0,3,5)
print(np.allclose(A,B))
print(np.array_equal(A,B))

False
False


## ***43. Make an array immutable (read-only) (★★☆) ***
(**hint**: flags.writeable)

In [ ]:
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1

ValueError: ignored

### *** 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) ***
(**hint**: np.sqrt, np.arctan2)

In [ ]:
a = np.random.random((10,2))
X,Y = a[:,0], a[:,1] # getting x and y coordinates seperately
radius = np.sqrt(X**2+Y**2)
theta = np.arctan2(Y,X)
print(radius)
print(theta)

[0.97418735 0.96069082 1.19775294 1.10589549 1.10157788 0.92694918
 0.61748041 0.4254165  1.31401316 1.27276154]
[1.23186888 0.85819974 0.80022128 0.66198382 1.13509925 0.62075866
 0.05984511 0.79577877 0.75593148 0.84324318]


## ***45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) ***
(**hint**: argmax)

In [ ]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.         0.8448532  0.92672338 0.68498783 0.6727424  0.38689164
 0.93621177 0.53453088 0.56391266 0.66593141]


### *** 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) ***
(**hint**: np.meshgrid)

In [ ]:
z = np.zeros((5,5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))

print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X = np.arange(8)
Y = X + 0.5

C = 1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.163637117973


 *** 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) ***
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
np.set_printoptions(threshold=0)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## ***49. How to print all the values of an array? (★★☆) ***
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=float("inf"))
X = np.zeros((5,5))
print(X)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### ***50. How to find the closest value (to a given scalar) in a vector? (★★☆) ***
(**hint**: argmin)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(v)
print(Z[index])

72.72379747249065
73


### ***51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) ***
(**hint**: dtype)

In [ ]:
np.array([], dtype=[('position',[('x',np.int32), ('y',np.int32)]),
                     ('color', [('r', np.int32), ('g', np.int32),('b', np.int32)])])

array([],
      dtype=[('position', [('x', '<i4'), ('y', '<i4')]), ('color', [('r', '<i4'), ('g', '<i4'), ('b', '<i4')])])

### ***52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) ***
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.05208291 0.35386368 ... 0.2842292  0.44712084 0.40827016]
 [0.05208291 0.         0.30582841 ... 0.24646773 0.41181199 0.35764264]
 [0.35386368 0.30582841 0.         ... 0.12452297 0.18849087 0.077645  ]
 ...
 [0.2842292  0.24646773 0.12452297 ... 0.         0.16587031 0.20211492]
 [0.44712084 0.41181199 0.18849087 ... 0.16587031 0.         0.23958459]
 [0.40827016 0.35764264 0.077645   ... 0.20211492 0.23958459 0.        ]]


### ***53. How to convert a float (32 bits) array into an integer (32 bits) in place? ***
(**hint**: astype(copy=False))

In [ ]:
x = np.arange(10, dtype=np.float32)
x = x.astype(np.int32, copy=False)
print(x)

[0 1 2 ... 7 8 9]


### ***54. How to read the following file? (★★☆) ***
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


### ***55. What is the equivalent of enumerate for numpy arrays? (★★☆) ***
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### ***56. Generate a generic 2D Gaussian-like array (★★☆) ***
(**hint**: np.meshgrid, np.exp)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 ...
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]]


### ***57. How to randomly place p elements in a 2D array? (★★☆) ***
(**hint**: np.put, np.random.choice)

In [ ]:
n = 5
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


## ***58. Subtract the mean of each row of a matrix (★★☆) ***
(**hint**: mean(axis=,keepdims=))

In [ ]:
X = np.random.rand(4,5)
Y = X - X.mean(axis=1, keepdims=True)
Y

array([[ 0.32257833,  0.0171926 , -0.42489328,  0.31286642, -0.22774407],
       [-0.13632807,  0.06775042,  0.32401708,  0.09939387, -0.35483331],
       [ 0.30906002, -0.20870103,  0.38374332, -0.17707453, -0.30702779],
       [ 0.18751425, -0.20766249, -0.10210554,  0.01316255,  0.10909123]])

## ***59. How to sort an array by the nth column? (★★☆) ***
(**hint**: argsort)

In [ ]:
x = np.random.randint(0,100,(3,3))
print(x)
x[x[:,1].argsort()]

[[83 46 38]
 [33 31 47]
 [91 70  2]]


array([[33, 31, 47],
       [83, 46, 38],
       [91, 70,  2]])

## ***60. How to tell if a given 2D array has null columns? (★★☆) ***
(**hint**: any, ~)

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


## ***61. Find the nearest value from a given value in an array (★★☆) ***
(**hint**: np.abs, argmin, flat)

In [ ]:
X = np.random.uniform(0,1,5)
value = 0.5
y = X.flat[np.abs(X-value).argmin()]
y

0.63169936273641

### ***62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) ***
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


### ***63. Create an array class that has a name attribute (★★☆) ***
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


### ***64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) ***
(**hint**: np.bincount | np.add.at)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[3. 3. 5. ... 2. 3. 2.]
[5. 5. 9. ... 3. 5. 3.]


## ***65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) ***
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


### ***66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) ***
(**hint**: np.unique)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(np.reshape(I, h*w*3))
n = len(colors)
print(n)

4


### ***67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) ***
(**hint**: sum(axis=(-2,-1)))

In [ ]:
X = np.arange(16).reshape(2,2,2,2)
X.sum(axis=(-2,-1))

array([[ 6, 22],
       [38, 54]])

68. **Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?** (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sum = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sum / D_counts
print(D_means)

[0.48355375 0.34066724 0.438949   0.46920906 0.43896222 0.61940663
 0.57863706 0.52759007 0.33977564 0.60554898]


#### **69. How to get the diagonal of a dot product?** (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.randint(1,5,(5,5))
B = np.random.randint(1,5,(5,5))
np.diag(np.dot(A, B))

array([36, 15, 23, 32, 23])

#### **70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value?** (★★★) 
(**hint**: array\[::4\])

In [ ]:
X = np.array([1,2,3,4,5])
num_zeros = 3
X_0 = np.zeros(len(X) + (len(X)-1)*(num_zeros))
X_0[::num_zeros+1] = X
print(X_0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### ***71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? ***(★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))
B = np.ones((5,5))
print(A * B[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


#### **72. How to swap two rows of an array?** (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
X = np.arange(25).reshape(5,5)
print(X)
X[[0,1]] = X[[1,0]]
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### ***73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles ***(★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0,  2) ( 0, 99) ( 1, 90) ( 1, 94) ( 2, 99) ( 5, 66) ( 5, 95) ( 7, 41)
 ( 7, 74) ( 8, 24) ( 8, 79) (11, 18) (11, 66) (18, 66) (24, 29) (24, 72)
 (24, 79) (29, 72) (37, 47) (37, 53) (40, 70) (40, 87) (41, 74) (47, 53)
 (61, 63) (61, 88) (63, 88) (66, 95) (70, 87) (90, 94)]


#### **74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?** (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(C,np.bincount(A))

[0 2 1 1 2 0 1] [0 2 1 1 2 0 1]


#### **75. How to compute averages using a sliding window over an array?** (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### **76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\])** (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def rolling_array(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling_array(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. ***How to negate a boolean, or to change the sign of a float inplace? ***(★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.38402694, -0.76585757,  0.06001244,  0.95796618,  0.54613368,
       -0.5206833 , -0.89938558,  0.24862303,  0.99060001, -0.59267878,
        0.75944182,  0.09193092, -0.41105319,  0.74459537, -0.14164561,
       -0.33160194, -0.25976339, -0.46510642,  0.42968453, -0.26559457,
        0.93105917, -0.27370246, -0.064833  , -0.25039056,  0.18181884,
       -0.87775782, -0.66975832,  0.60037282, -0.22356288, -0.57194977,
        0.4260319 ,  0.87875778, -0.10825051,  0.56949316,  0.1681574 ,
        0.8592347 ,  0.18124299,  0.35168287,  0.82552682,  0.40686139,
       -0.26037923, -0.91774383, -0.95445556, -0.90900764,  0.73589704,
       -0.18961716, -0.42165897, -0.51789741, -0.25191907, -0.93720849,
        0.83772182,  0.04537855, -0.39337007,  0.65390058, -0.26447063,
        0.86248298, -0.00161798,  0.490358  ,  0.55292756, -0.05535256,
       -0.57007792,  0.63147892,  0.72760667,  0.43893133,  0.74601607,
        0.43802988,  0.15982397, -0.54548848, -0.83386623, -0.77

#### **78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])?** (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[6.94174831 5.96093999 7.06459344 3.1897711  5.37183259 3.91487319
 3.89674668 2.54395062 3.18312954 4.98052081]


####*** 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])?*** (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[1.03162304e+01 1.61342771e+01 4.59279047e+00 4.72734895e+00
  8.68071724e+00 2.38500981e-01 1.10581287e-01 4.54838952e+00
  1.62238155e+00 1.28936314e+00]
 [8.55158351e+00 1.55750984e+01 6.56766253e+00 2.53617143e+00
  1.04016619e+01 1.67084750e+00 1.54328526e+00 5.66555156e+00
  4.71413817e-01 3.24139999e+00]
 [2.03112725e+00 3.55718915e-01 7.55020954e+00 1.37945159e+01
  5.58220790e+00 1.55671333e+01 9.25453478e+00 1.23015679e+01
  1.14382361e+01 7.38747574e+00]
 [1.48520948e+01 1.53376561e+01 4.12058540e+00 1.36468021e+01
  4.62474079e-01 7.26981063e+00 4.08992817e+00 2.07580651e+00
  3.28041292e+00 4.24903500e+00]
 [4.53134216e+00 1.33993574e+01 9.59857153e+00 1.12878421e+00
  1.27904632e+01 3.38928999e+00 5.42085410e+00 6.69579445e+00
  2.67570137e+00 7.47828897e+00]
 [4.69456463e+00 8.64417092e+00 1.58962448e+00 6.14723321e+00
  4.46596152e+00 4.97712354e+00 5.85265587e+00 1.48231594e+00
  5.36745183e+00 6.17695556e+00]
 [7.79188893e+00 8.78202941e+00 3.25020857e+00 1.12345864e

#### **80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)** (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[6 1 2 3 2 2 8 1 2 9]
 [1 1 0 6 1 2 9 7 1 5]
 [3 1 1 2 6 5 6 7 8 4]
 [2 8 3 2 0 5 3 0 2 3]
 [9 8 9 9 3 6 1 9 3 8]
 [4 6 9 6 0 0 6 3 9 7]
 [5 1 5 2 5 7 6 9 2 8]
 [5 0 8 4 6 6 5 7 5 7]
 [8 9 4 0 7 2 3 1 5 9]
 [8 9 8 8 4 9 9 6 7 0]]
[[0 0 0 0 0]
 [0 6 1 2 3]
 [0 1 1 0 6]
 [0 3 1 1 2]
 [0 2 8 3 2]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### **81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]?** (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.arange(1,15,dtype=np.int32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### **82. Compute a matrix rank** (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z = np.random.uniform(0,1,(10,10))

rank = np.linalg.matrix_rank(Z)
print(rank)

10


#### ***83. How to find the most frequent value in an array? ***
(**hint**: np.bincount, argmax)

In [ ]:
X = np.random.randint(0,10,50)
print(X)
print(np.bincount(X).argmax())

[7 3 1 2 2 3 5 8 0 8 4 6 0 4 4 1 8 3 3 9 5 6 8 0 3 8 1 8 2 3 2 1 7 2 6 8 7
 5 7 6 8 0 7 4 0 1 0 7 1 4]
8


#### **84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix** (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 2 1]
   [2 0 4]
   [1 0 2]]

  [[2 1 1]
   [0 4 2]
   [0 2 2]]

  [[1 1 1]
   [4 2 2]
   [2 2 1]]

  [[1 1 2]
   [2 2 2]
   [2 1 2]]

  [[1 2 0]
   [2 2 3]
   [1 2 3]]

  [[2 0 0]
   [2 3 1]
   [2 3 1]]

  [[0 0 4]
   [3 1 1]
   [3 1 1]]

  [[0 4 0]
   [1 1 1]
   [1 1 0]]]


 [[[2 0 4]
   [1 0 2]
   [2 2 3]]

  [[0 4 2]
   [0 2 2]
   [2 3 1]]

  [[4 2 2]
   [2 2 1]
   [3 1 3]]

  [[2 2 2]
   [2 1 2]
   [1 3 4]]

  [[2 2 3]
   [1 2 3]
   [3 4 0]]

  [[2 3 1]
   [2 3 1]
   [4 0 2]]

  [[3 1 1]
   [3 1 1]
   [0 2 1]]

  [[1 1 1]
   [1 1 0]
   [2 1 4]]]


 [[[1 0 2]
   [2 2 3]
   [3 4 4]]

  [[0 2 2]
   [2 3 1]
   [4 4 4]]

  [[2 2 1]
   [3 1 3]
   [4 4 4]]

  [[2 1 2]
   [1 3 4]
   [4 4 4]]

  [[1 2 3]
   [3 4 0]
   [4 4 1]]

  [[2 3 1]
   [4 0 2]
   [4 1 1]]

  [[3 1 1]
   [0 2 1]
   [1 1 1]]

  [[1 1 0]
   [2 1 4]
   [1 1 2]]]


 [[[2 2 3]
   [3 4 4]
   [1 1 4]]

  [[2 3 1]
   [4 4 4]
   [1 4 1]]

  [[3 1 3]
   [4 4 4]
   [4 1 2]]

  [[1 3 4]
   [4 4 4]
   [1 2 0]]

  [[3 4 0]
   

####*** 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\]*** (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3 14  9 11  8]
 [14  7  4  4  5]
 [ 9  4  6 42 11]
 [11  4 42  3  6]
 [ 8  5 11  6  5]]


#### ***86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) ***(★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S.shape)

(20, 1)


#### 87. **Consider a 16x16 array, how to get the block-sum (block size is 4x4)?** (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### **88. How to implement the Game of Life using numpy arrays?** (★★★)

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### **89. How to get the n largest values of an array** (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


####*** 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)*** (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### **91. How to create a record array from a regular array?** (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z = np.array([("Welcome", 7.4, 3),
              ("Home", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Welcome', 7.4, 3) (b'Home', 3.6, 2)]


#### ***92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods ***(★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e5))
print(np.power(x,3))
print(x*x*x)
print(np.einsum('i,i,i->i',x,x,x))

[0.07600733 0.82910578 0.14469145 ... 0.01943436 0.00301946 0.22869287]
[0.07600733 0.82910578 0.14469145 ... 0.01943436 0.00301946 0.22869287]
[0.07600733 0.82910578 0.14469145 ... 0.01943436 0.00301946 0.22869287]


####*** 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?*** (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print(A,B,sep='\n')
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[[2 0 3]
 [2 3 2]
 [0 4 2]
 [1 4 3]
 [4 3 2]
 [0 2 4]
 [1 2 1]
 [1 0 4]]
[[3 1]
 [2 4]]
[0 1 3 4 6 7]


#### **94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\])** (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[3 4 3]
 [1 3 0]
 [2 0 1]
 [2 2 2]
 [4 4 1]
 [4 4 2]
 [1 2 3]
 [4 3 4]
 [0 4 0]
 [2 4 4]]
[[3 4 3]
 [1 3 0]
 [2 0 1]
 [4 4 1]
 [4 4 2]
 [1 2 3]
 [4 3 4]
 [0 4 0]
 [2 4 4]]


#### **95. Convert a vector of ints into a matrix binary representation** (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### ***96. Given a two dimensional array, how to extract unique rows? ***(★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
X = np.array([[1,2,3],[1,2,3],[1,2,3],[4,5,6],[7,8,9]])
print(X)
unique_rows = np.unique(X, axis=0)
print(unique_rows)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### **97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function** (★★★) 
(**hint**: np.einsum)

In [ ]:
#A = np.random.uniform(0,1,10)
#B = np.random.uniform(0,1,10)
A = 2*np.ones(5)
B = 3*np.ones(5)
print(A)
print(B)
print("Sum", np.einsum('i->', A))      # np.sum(A)
print("Product",np.einsum('i,i->i', A, B)) # A * B
print("Inner",np.einsum('i,i', A, B))   # np.inner(A, B)
print("Outer",np.einsum('i,j->ij', A, B))    # np.outer(A, B)

[2. 2. 2. 2. 2.]
[3. 3. 3. 3. 3.]
Sum 10.0
Product [6. 6. 6. 6. 6.]
Inner 30.0
Outer [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


#### **98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples** (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### **99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.** (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### **100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).** (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100)
N = 1000 # number of samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confidence = np.percentile(means, [5, 95])
print(confidence)

[-0.08408551  0.22251101]
